MODEL:
  TYPE: eva02_meta_cloth
  NAME: eva02_meta_cloth_l
  META_DIMS: [ 105, ]
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NO_MARGIN: True
  ADD_META: True
  MASK_META: True

DATA:
  IMG_HEIGHT: 224
  IMG_WIDTH: 224
  DATASET: 'celeb_light'

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 60
  BASE_LR: 2e-5
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 60
  LOG_PERIOD: 50
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  0.05
  WEIGHT_DECAY_BIAS: 0.05
  BIAS_LR_FACTOR: 2

TEST:
  WEIGHT: ''
  FEAT_NORM: 'yes'
  TYPE: 'image_only'
OUTPUT_DIR: '../MADE/logs/Celeb'


